variable "instance_count" {}
variable "instance_type" {}
variable "public_sg" {}
variable "public_subnet" {}
variable "vol_size" {}
variable "key_name" {}
variable "public_key_path" {}
variable "user_data_pth" {}
variable "dbuser" {}
variable "dbpassword" {}
variable "db_endpoint" {}
variable "dbname" {}
variable "target_group_arn" {}
variable "tg_attach_port" {}
variable "private_key_path" {}